name: safezone
description: Een veilige route-app met live kaart en locatie
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.1.0
  geolocator: ^13.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
